### ISSUE TITLE
Reporte con Items con Precio Unitario (+igv)

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-report#10]
hola amigo, como se puede hacer para que en el reporte salgan los items con el igv incluido

**Comment by giansalex** [comment]
No se visualizan los items?

**Comment by abelnexus** [comment]
si se muestra pero sin igv(valor unitario) y necesito que se muestre ya con el igv(precio unitario)
![Captura](https://user-images.githubusercontent.com/34687414/59465015-89328380-8def-11e9-836b-ac32a43d7ac8.PNG)

**Comment by giansalex** [comment]
Como indica en la columna es el precio unitario, tendrías que editar la plantilla para lo que necesitas o crear una propia según tus necesidades.

**Comment by abelnexus** [comment]
fue mas sencillo de lo que imaginaba, por si alguien mas necesita solo hay que cambiar por estos datos:
                        <td align="center">
                                {{ moneda }}
                                {{ det.MtoPrecioUnitario|n_format }}
                         </td>

                            <td align="center">
                                {{ moneda }}
                                {{ det.MtoPrecioUnitario*det.Cantidad|n_format }}
                            </td>
