### ISSUE TITLE
New report template

### ISSUE THREAD

**Issue by giansalex** [giansalex/greenter-report#2]
- Add this [model](https://app.stupendo.pe/documento/receptor/5a0af9c42c72b961fc51e01c)

**Comment by abelnexus** [comment]
wow como se sacaria ese aspecto :o

**Comment by giansalex** [comment]
Este es el modelo en html que pude extraer.
[index.zip](https://github.com/giansalex/greenter-report/files/1646836/index.zip)

**Comment by abelnexus** [comment]
seria mas facil convertirlo en pdf a hacerlo con fpdf verdad ?

**Comment by giansalex** [comment]
Si, aunque si tienes experiencia usando esa librería también te resultaría rápido.
Este es el resultado de convertir el html a pdf usando wkhtmltopdf.exe:
[invoice.pdf](https://github.com/giansalex/greenter-report/files/1647884/invoice.pdf)

**Comment by abelnexus** [comment]
seria genial si le agregaras este reporte grafico a greenter-sample

**Comment by giansalex** [comment]
Creare otro repositorio con wkhtmltopdf para obtener el PDF, ahora mismo he agregado el nuevo modelo como Reporte Html, tambien la generacion de CodigoQR
