### ISSUE TITLE
Print Ticket Format

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-report#3]
amigo para emitir tickets, es un documento diferente o solo es una factura con el aspecto diferente no hay en sunat informacion sobre tickets electronicos(para dar comprobantes con esas maquinas que imprimen tickets )

**Comment by giansalex** [comment]
Como comprobante no hay ticket electronico, de si puedes imprimir la factura en esas impresoras.

**Comment by abelnexus** [comment]
entonces solo es la factura en tamaño de ticket, ahora modificar el template o tenras algun tempalte de ticket amigo

**Comment by giansalex** [comment]
no se me ha presentado esa necesidad, pero seria favorable para este proyecto que si lo realizas puedas compartirlo.
Si necesitas convertirlo a pdf, tendras que cambiar esta linea, donde se coloca las dimensiones de la hoja.
https://github.com/giansalex/greenter-sample/blob/ef862b9bf470b94431029358879ea560b9db5d6f/src/Util.php#L85
```php
        $render = new PdfReport($html);
        $render->setOptions( [
            'no-outline',
            'viewport-size' => '1280x1024', 
            'page-width' => '21cm', 
            'page-height' => '29.7cm', 
            'footer-html' => __DIR__.'/../resources/footer.html',
        ]);
```

**Comment by abelnexus** [comment]
haré lo mejor que pueda y lo compartire

**Comment by giansalex** [comment]
tiene la opción para [insertar imagen](http://www.fpdf.org/es/doc/image.htm) , que en esa opcion se puede insertar el codigo Qr, el cual segun la norma era obligatoria apartir de este año.

**Comment by abelnexus** [comment]
hola amigo, lo intente con fpdf y no logre nada :'( estoy haciendo ahora con wkhtmltopdf y tengo un problema 
1.- como hago para que el largo sea automatico,
2.- como se elimina el espacio de los costados (no encuentro el padding que lo hace)

**Comment by abelnexus** [comment]
![captura](https://user-images.githubusercontent.com/34687414/38817081-3a02a2a2-415d-11e8-9783-b61cf18f0092.PNG)

**Comment by abelnexus** [comment]
ahi se ve pequeño pero al imprimir se vuelve grande XD

**Comment by giansalex** [comment]
En las [opciones del wkhtmltopdf](https://github.com/giansalex/greenter-sample/blob/master/src/Util.php#L86) puedes agregar estos puntos `'margin-left' => 0` y `'margin-right' => 0` , todas las opciones estan en la [pagina oficial](https://wkhtmltopdf.org/docs.html)

**Comment by abelnexus** [comment]
![captura](https://user-images.githubusercontent.com/34687414/38822697-d6ae1d8c-4169-11e8-9c7c-7363e1627bea.PNG)

**Comment by abelnexus** [comment]
ya tiene mas forma de ticket, pero el problema sigue siendo que se divide

**Comment by giansalex** [comment]
hay un problema con wkhtmltopdf, no tiene la opción de height automático, he estado siguiendo este [issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1627) donde se habla al respecto pero aun no hay un parche disponible, si tienes el html puedes compartirlo para probar con otra herramiente

**Comment by abelnexus** [comment]
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style type="text/css">
        {% include 'assets/style.css' %}
    </style>
</head>
<body class="white-bg">
{% set cp = doc.company %}
{% set isNota = doc.tipoDoc in ['07', '08'] %}
{% set isAnticipo = doc.totalAnticipos is defined and doc.totalAnticipos > 0 %}
{% set name = doc.tipoDoc|catalog('01') %}
<table width="35%" cellpadding="0" cellspacing="0">
    <tbody><tr>
        <td style="padding:0px; !important">
            <table width="100%" height="200px" border="0" aling="center" cellpadding="0" cellspacing="0">
                <tbody><tr>
                     
                    <td valign="bottom" style="padding-left:0">
                        
                            <table width="100%" height="100%" border="0" border-radius="" cellpadding="9" cellspacing="0">
                                <tbody>
                                    <tr>
                                    <td align="center">

                                        <strong><span style="font-size:20px">{{ cp.razonSocial }}</span></strong><br>
                                        <span style="font-size:15px" text-align="center">R.U.C.: {{ cp.ruc }}</span><br>
                       
                                   
                                        <strong>Dirección: </strong>{{ cp.address.direccion }}
                                    </td>
                                
                                <tr>
                                    <td align="center">
                                        <span style="font-family:Tahoma, Geneva, sans-serif; font-size:20px" text-align="center">{{ name }}</span>
                                        <br>
                                        <span style="font-family:Tahoma, Geneva, sans-serif; font-size:15px" text-align="center">E L E C T R Ó N I C A</span>
                                    </td>
                                </tr>
                            
                                <tr>
                                    <td align="center">
                                        No.: <span>{{ doc.serie }}-{{ doc.correlativo }}</span>
                                    </td>
                                </tr>
                                <tr>
                                     {% set cl = doc.client %}
                        <td width="60%" align="left"><strong>Razón Social:</strong>  {{ cl.rznSocial }}<br>
                            <strong>{{ cl.tipoDoc|catalog('06') }}:</strong>  {{ cl.numDoc }}<br>
                             <strong>Dirección: </strong>  {% if cl.address %}{{ cl.address.direccion }}{% endif %} <br>     
                            <strong>Fecha Emisión: </strong>  {{ doc.fechaEmision|date('d/m/Y') }}<br>
                            {% if doc.fecVencimiento is defined and doc.fecVencimiento %}
                            <br><br><strong>Fecha Vencimiento: </strong>  {{ doc.fecVencimiento|date('d/m/Y') }}<br>
                            {% endif %}              
                    {% if isNota %}
                    <strong>Tipo Doc. Ref.: </strong>  {{ doc.tipDocAfectado|catalog('01') }}
                    <strong>Documento Ref.: </strong>  {{ doc.numDocfectado }}
                    
                    {% endif %}
                                         
                        <strong>Tipo Moneda: </strong>  {{ doc.tipoMoneda|catalog('021') }}
                       {% if doc.compra is defined and doc.compra %}<strong>O/C: </strong>  {{ doc.compra }}{% endif %}
                                                                 
                                </tbody></table>
                        
                    </td>
                </tr>
                </tbody></table>     
            {% set moneda = doc.tipoMoneda|catalog('02') %}
            
                <table width="100%" border="0" cellpadding="5" cellspacing="0">
                    <tbody>
                        <tr>
                            <td align="center" class="bold">Cantidad</td>
                            
                            <td align="center" class="bold">Descripción</td>
                            <td align="center" class="bold">Valor Unitario</td>
                            <td align="center" class="bold">Valor Total</td>
                        </tr>
                        {% for det in doc.details %}
                        <tr class="border_top">
                            <td align="center">
                                {{ det.cantidad|n_format }}
                                {{ det.unidad }}
                            </td>                        
                            <td align="center" width="300px">
                                <span>{{ det.descripcion }}</span><br>
                            </td>
                            <td align="center">
                                {{ moneda }}
                                {{ det.mtoValorUnitario|n_format }}
                            </td>
                            <td align="center">
                                {{ moneda }}
                                {{ det.mtoValorVenta|n_format }}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            <table width="100%" border="0" cellpadding="0" cellspacing="0">
                <tbody><tr>
                    <td width="100%" valign="top">
                        <table width="80%" border="0" cellpadding="5" cellspacing="0">
                            <tbody>
                                     {% if isAnticipo %}
                                <tr class="border_bottom">
                                    <td align="right"><strong>Total Anticipo:</strong></td>
                                    <td width="250" align="right"><span>{{ moneda }}  {{ doc.totalAnticipos|n_format }}</span></td>
                                </tr>
                            {% endif %}
                            {% if doc.mtoOperGravadas %}
                            <tr class="border_top">
                                <td align="right"><strong>Gravadas:</strong></td>
                                <td width="250" align="right"><span>{{ moneda }}  {{ doc.mtoOperGravadas|n_format }}</span></td>
                            </tr>
                            {% endif %}
                            {% if doc.mtoOperInafectas %}
                            <tr class="border_bottom">
                                <td align="right"><strong>Op. Inafectas:</strong></td>
                                <td width="250" align="right"><span>{{ moneda }}  {{ doc.mtoOperInafectas|n_format }}</span></td>
                            </tr>
                            {% endif %}
                            {% if doc.mtoOperExoneradas %}
                            <tr class="border_bottom">
                                <td align="right"><strong>Op. Exoneradas:</strong></td>
                                <td width="250" align="right"><span>{{ moneda }}  {{ doc.mtoOperExoneradas|n_format }}</span></td>
                            </tr>
                            {% endif %}
                            <tr class="border_top">
                                <td align="right"><strong>IGV:</strong></td>
                                <td width="250" align="right"><span>{{ moneda }}  {{ doc.mtoIGV|n_format }}</span></td>
                            </tr>
                            {% if doc.mtoISC %}
                            <tr>
                                <td align="right"><strong>ISC:</strong></td>
                                <td width="250" align="right"><span>{{ moneda }}  {{ doc.mtoISC|n_format }}</span></td>
                            </tr>
                            {% endif %}
                            {% if  doc.sumOtrosCargos %}
                                <tr>
                                    <td align="right"><strong>Otros Cargos:</strong></td>
                                    <td width="250" align="right"><span>{{ moneda }}  {{ doc.sumOtrosCargos|n_format }}</span></td>
                                </tr>
                            {% endif %}
                            {% if doc.mtoOtrosTributos %}
                                <tr>
                                    <td align="right"><strong>Otros Tributos:</strong></td>
                                    <td width="250" align="right"><span>{{ moneda }}  {{ doc.mtoOtrosTributos|n_format }}</span></td>
                                </tr>
                            {% endif %}
                            <tr class="border_top">
                                <td align="right"><strong>Precio Venta:</strong></td>
                                <td width="250" align="right"><span id="ride-importeTotal" class="ride-importeTotal">{{ moneda }}  {{ doc.mtoImpVenta|n_format }}</span></td>
                            </tr>
                            {% if doc.perception and doc.perception.mto %}
                                {% set perc = doc.perception %}
                                {% set soles = 'PEN'|catalog('02') %}
                                <tr>
                                    <td align="right"><strong>Percepción:</strong></td>
                                    <td width="120" align="right"><span>{{ soles }}  {{ perc.mto|n_format }}</span></td>
                                </tr>
                                <tr>
                                    <td align="right"><strong>Total</strong></td>
                                    <td width="120" align="right"><span>{{ soles }}  {{ perc.mtoTotal|n_format }}</span></td>
                                </tr>
                            {% endif %}
                            <tr>
                                <td colspan="4">                                   
                                    <br>
                                    <span style="font-family:Tahoma, Geneva, sans-serif; font-size:12px" text-align="center"><strong>{{ legend(doc.legends, '1000')  }}</strong></span>
                                    <br>
                                    <br>
                                    <strong>Información Adicional</strong>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <table width="100%" border="0" cellpadding="5" cellspacing="0">
                            <tbody>
                            <tr class="border_top">
                                <td width="100%" style="font-size: 10px;">
                                    LEYENDA:
                                </td>
                                <td width="100%" style="font-size: 10px;">
                                    <p>
                                        {% for leg in doc.legends %}
                                        {% if leg.code != '1000' %}
                                            {{ leg.value }}<br>
                                        {% endif %}
                                        {% endfor %}
                                    </p>
                                </td>
                            </tr>
                            {% if isNota %}
                            <tr class="border_top">
                                <td width="30%" style="font-size: 10px;">
                                    MOTIVO DE EMISIÓN:
                                </td>
                                <td width="70%" style="font-size: 10px;">
                                    {{ doc.desMotivo }}
                                </td>
                            </tr>
                            {% endif %}
                            {% if params.user.extras is defined %}
                                {% for item in params.user.extras %}
                                    <tr class="border_top">
                                        <td width="30%" style="font-size: 10px;">
                                            {{ item.name|upper }}:
                                        </td>
                                        <td width="70%" style="font-size: 10px;">
                                            {{ item.value }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                            </tbody>
                        </table>
                        {% if isAnticipo %}
                        <table width="100%" border="0" cellpadding="5" cellspacing="0">
                            <tbody>
                            <tr>
                                <td>
                                    <br>
                                    <strong>Anticipo</strong>
                                    <br>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <table width="100%" border="0" cellpadding="5" cellspacing="0" style="font-size: 10px;">
                            <tbody>
                            <tr>
                                <td width="30%"><b>Nro. Doc.</b></td>
                                <td width="70%"><b>Total</b></td>
                            </tr>
                            {% for atp in doc.anticipos %}
                            <tr class="border_top">
                                <td width="30%">{{ atp.nroDocRel }}</td>
                                <td width="70%">{{ moneda }} {{ atp.total|n_format }}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        {% endif %}
                    </td>
                    <td width="50%" valign="top">
                        <br>
                        <table width="100%" border="0" cellpadding="0" cellspacing="0" class="table table-valores-totales">
                            <tbody>
                       
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody></table>
            <br>
            <br>
            {% if max_items is defined and doc.details|length > max_items %}
                <div style="page-break-after:always;"></div>
            {% endif %}
            <div>
                <hr style="display: block; height: 1px; border: 0; border-top: 1px solid #666; margin: 20px 0; padding: 0;"><table width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tbody>
                        <tr>
                                <td width="25%" align="center">
                            <img src="{{ qrCode(doc)|image_b64 }}" alt="Qr Image">
                        </td>
                    </tr>
                        <tr>
                         
                        <td width="85%">
                            <blockquote>
                                {% if params.user.footer is defined %}
                                    {{ params.user.footer|raw }}
                                {% endif %}
                                {% if params.system.hash is defined and params.system.hash%}
                                    <strong>Resumen:</strong>   {{ params.system.hash }}<br>
                                {% endif %}
                                <span>Representación Impresa de la {{ name }} ELECTRÓNICA.</span>
                            </blockquote>
                        </td>
                         
                  
                    </tr>
                    </tbody></table>
            </div>
        </td>
    </tr>
    </tbody></table>
</body></html>

**Comment by abelnexus** [comment]
ahora si le pongo 30cm en height si sale, pero se que habra problemas ya que es una altura fija

**Comment by giansalex** [comment]
Si esa es un temporal solucion, tener que calular la altura dependiendo principalmente de la cantidad de registros de la venta.

> queria el html generado en un archivo .html

**Comment by abelnexus** [comment]
vale te lo hize desde el invoice.twig , pero ahorita lo ahgo en html

**Comment by giansalex** [comment]
He agregado la opción de obtener el html que se usa para generar el pdf, aqui esta [un ejemplo](https://github.com/giansalex/greenter-sample/blob/master/src/Util.php#L107)

**Comment by abelnexus** [comment]
use el template de bumeran https://github.com/giansalex/greenter-report/files/1647884/invoice.pdf de ese ejemplo

**Comment by giansalex** [comment]
he actualizado tu comentario para adjuntar el html y pdf generado apartir de wkhtmltopdf

**Comment by abelnexus** [comment]
hola amigo, tengo un problema y no puedo solucionarlo, el formato de ticket me funciona correctamente en boletas y factura pero tengo problemas con la guia de remision ya que tambien se crea con el formato de "ticket" y sale mal impreso. hay alguna forma de eligir otro tempalte para guia de remision ?
![captura](https://user-images.githubusercontent.com/34687414/39309035-ae2af0fe-492c-11e8-97bd-479a1f2fc664.PNG)

**Comment by abelnexus** [comment]
sale asi por las dimenciones que le doy en 
            'no-outline',
            'page-width' => '50mm',
            'page-height' => '250mm',
            'margin-left' => 0,
            'margin-right' => 0,
        ]);

**Comment by giansalex** [comment]
Aunque no he visto una guía de remisión en formato de Ticket, tendría que hacerse un formato de Ticket similar al que hiciste con la Factura.

**Comment by giansalex** [comment]
@abelnexus apartir de agosto entraran empezar a operar los OSE, se tendrá que pagarles a ellos, aunque esto no va ser obligatorio para todos sera paulatino para aquellos que ya tienen su sistema de facturación electrónica.

**Comment by thefantas** [comment]
Nunca subieron el template del ticket.
Por cierto lo de las medidas lo puedes trabajar con mysql, por ejemplo grabando los parámetros del movimiento o tipo de documento que está haciendo.

**Comment by giansalex** [comment]
Lo que buscábamos era que el pdf del ticket se extendiera según el contenido, lo unico que se podria hacer es colocar el alto segun la cantidad de registros.

**Comment by giansalex** [comment]
> command:
> `wkhtmltopdf -B 0 -L 0 -R 0 -T 0 --page-width 70mm --page-height 320mm ticket.html ticket.pdf`

Ya ha pasado tiempo, la solución sera calcular la altura aproximada dependiendo de la cantidad de items del comprobante.

**Comment by GMSOLUCIONES** [comment]
La solución al PDF incompleto puede ser este algoritmo de FPDF

http://www.fpdf.org/en/script/script101.php
http://www.fpdf.org/en/script/ex101.pdf

**Comment by GMSOLUCIONES** [comment]
> Serán los que ayuden a Sunat en esa labor, pero no estoy seguro de si Sunat dejara de recibir comprobantes, en todo caso solo quedaría enviar al OSE.



> > command:
> > `wkhtmltopdf -B 0 -L 0 -R 0 -T 0 --page-width 70mm --page-height 320mm ticket.html ticket.pdf`
> 
> Ya ha pasado tiempo, la solución sera calcular la altura aproximada dependiendo de la cantidad de items del comprobante.

La solución al PDF incompleto puede ser este algoritmo de FPDF

http://www.fpdf.org/en/script/script101.php
http://www.fpdf.org/en/script/ex101.pdf
