### ISSUE TITLE
Usar un template personalizado

### ISSUE THREAD

**Issue by KhanMaytok** [giansalex/greenter-report#6]
Hola, como puedo usar un template con otro diseño? He visto que en método setTemplate solo se le pasa el nombre, por ejemplo, 'invoice.html.twig'

Se le puede pasar la ruta que contiene el nuevo template?

**Comment by giansalex** [comment]
Hola @KhanMaytok , puedes pasar la ruta del directorio donde se encuentra tus plantillas personalizadas, desde el [constructor](https://github.com/giansalex/greenter-report/blob/7dafa09852a0f4963b9cd5f3c0c5ae6c727c0841/src/Report/HtmlReport.php#L36)
