### ISSUE TITLE
Twig 2 Soporte para usar con Symfony 4.3

### ISSUE THREAD

**Issue by Ajahuanex** [giansalex/greenter-report#8]
Como puedo instalarlo en symfony 4.3 ya que me sale el siguiente error.
![Screenshot_21](https://user-images.githubusercontent.com/2767765/58767814-4bfc0500-8556-11e9-9a3d-627fae914de4.png)

**Comment by giansalex** [comment]
Al parecer hay un conflicto con `swiftmailer-bundle`, si no lo usas puedes quitarlo.

**Comment by Ajahuanex** [comment]
el problema persiste al quitar `composer remove symfiny/swiftmailer-bundle`, ya que había conflictos con otras dependencias propias de `greenter/report`, por ejemplo con `twig ` que son versiones que tienen conflictos con las dependencias de `symfony/website-skeleton` entonces, **funcionó** con `**symfony/skeleton**`.

**Comment by giansalex** [comment]
Si es por la version de twig que usa `greenter/report` aunque tambien estaria en conflicto `greenter/xml`, voy  a ver si puedo agregar la versión más reciente de twig en `composer.json`.

**Comment by Ajahuanex** [comment]
Efectivamente el conflicto de twig va tener repercuciones con las nuevas versiones de symfony 
 como el caso de la interface Twig_RuntimeLoaderInterface.
![Screenshot_23](https://user-images.githubusercontent.com/2767765/58813300-12c0a500-85e9-11e9-8219-beacccbc5b77.png)

**Comment by giansalex** [comment]
El problema principal es con twig, aun asi se puede usar con symfony en sus ultima version como el caso de APIs, ya que alli no hay dependencia de twig. 
De todas formas tengo planeado subir la version de PHP a 7.1 y poder usar la ultima version de twig.

**Comment by giansalex** [comment]
Hola @Ajahuanex , se agrego soporte para usarlo junto con twig v2, puedes instalar nuevamente el paquete.

**Comment by Ajahuanex** [comment]
Excelente, funciona de maravillas en Symfony 4.3.
